### ISSUE TITLE
Missing SCSYS in soles

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ergocub-software#12]
We are missing both `SCSYS_R_SOLE` and `SCSYS_L_SOLE` in the simmechanics xml

See https://github.com/search?q=repo%3Aicub-tech-iit%2Fergocub-software%20SCSYS_R_SOLE&type=code

cc @fiorisi @traversaro @pattacini @Lawproto @Mick3Lozzo @salvi-mattia

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/209352104-d0a2b3e1-9c2a-4df3-b927-8c6e5549909e.png" width="400">

@Nicogene they are present in the shrink-wrapped Creo 9 assembly....

<img src="https://user-images.githubusercontent.com/15085666/209352192-e3d09221-3fe1-410c-85ff-02a53467ff68.png" width="400">
 
.... but NOT in the shrink-wrapped Creo 7 assembly. That should not be possible, because we used the Creo 9 assembly as a source for the Creo 7 assembly. 💀💀

Well, we have to redo a couple of shrinkwraps. Maybe in some of the many passages back and fort we did, we lost something.

**Comment by Lawproto** [comment]
@Mick3Lozzo I exported a .neu of `SIM_ECUB_L_FOOT_REAR` on the fly and opened it in Creo7. I can see the SCSYS:

![immagine](https://user-images.githubusercontent.com/84333301/209354503-1d91de73-183f-4adc-be81-34d53935657a.png)

I suggest you recreate the two neutrals separately, overwrite the Creo 7 links and fix the assembly. Remember to reassign mass with the external file.

<details>
Hohoho! 🎅 
</details>

**Comment by Mick3Lozzo** [comment]
<img src="https://user-images.githubusercontent.com/15085666/209412648-6e1791d0-e88e-471f-b563-f5ceb7d4cbb1.png" width="400">

Added missing SCSYS @Nicogene.

**Comment by Nicogene** [comment]
The part on the yml files should be already configured for exporting the frames, as soon as @mfussi66 can regenerate the simmechanics XML we should have the frames in the urdf

**Comment by Nicogene** [comment]
Added in #20 and #21, closing!
