### ISSUE TITLE
r_sole and l_sole are not centered

### ISSUE THREAD

**Issue by Nicogene** [icub-tech-iit/ergocub-software#23]
#22 added the unit tests that checks if `l_sole` and `r_sole` are parallel.

It gives the following error:
```
l_sole_y is 0.07435, while r_sole_y is -0.07445 while they should be simmetric (diff : 0.0001 )
```

`sole_height` and `sole_x` seems fine instead

cc @salvi-mattia @traversaro @mfussi66 @pattacini @Mick3Lozzo

**Comment by salvi-mattia** [comment]
in cad model they r parallel

![immagine](https://user-images.githubusercontent.com/43994292/211299762-52fc55b3-957d-43ab-8b1f-b10bc223dfa3.png)

and they are parallel in the SW mechanism

![immagine](https://user-images.githubusercontent.com/43994292/211299961-88864a49-0b5d-4ec6-8733-1b3d34ec9ffc.png)

where does this misalignement came from??

**Comment by Nicogene** [comment]
I tried to compute from code the same transform as:

```
    iDynTree::Transform l_sole_H_r_sole = comp.getRelativeTransform(l_sole,r_sole);
    std::cerr<<"l_sole - r_sole "<<l_sole_H_r_sole.getPosition().toString()<<std::endl;
```

And I got:

```
l_sole - r_sole -5e-05 -0.1488 0
```
That is the same as the cad.

Since we are computing the alignment of the frames using the two transforms `root_link_H_r_sole` and `root_link_H_l_sole`, maybe the `root_link` frame is not perfectly centered?

cc @fiorisi @traversaro @Mick3Lozzo @salvi-mattia

**Comment by salvi-mattia** [comment]
the two soles' CSYS are off center
@Mick3Lozzo is investigating

![immagine](https://user-images.githubusercontent.com/43994292/211342238-06898a97-ddf3-478d-b9f4-282d7db14fd5.png)

![immagine](https://user-images.githubusercontent.com/43994292/211342340-452bc0da-f4f9-4b99-86d5-78b508fa2ade.png)

**Comment by Mick3Lozzo** [comment]
The problem is the placement of the upper body on the lower body, is merely a CAD assembling problem.

<img src="https://user-images.githubusercontent.com/15085666/211358884-4400213c-d460-49e7-93af-3ba3bb925d25.png" width="450">

⬆️Between the bright green supports of the torso pitch motor and the dark green plate housing the torso yay motor, there is a 0.1 mm gap in assembling the components without interference problems due to the tolerance chain.

<img src="https://user-images.githubusercontent.com/15085666/211359776-978340f1-a9b4-46ff-b7b2-f1de32832959.png" width="450">

⬆️  This gap should be equally distributed between the joint's left and right sides of the joint but is all on one side.  

<img src="https://user-images.githubusercontent.com/15085666/211360185-5bfb92bd-cf87-4e57-a8f8-fa0b80f9ee65.png" width="450">

⬆️  This `coincident` should be `offset 0.05 mm`.

I have corrected the misalignment, and now the robot is fully symmetrical again ⬇️.

<img src="https://user-images.githubusercontent.com/15085666/211360664-3e718cd4-0b8b-497f-9875-a022c7df9985.png" width="450">

<img src="https://user-images.githubusercontent.com/15085666/211360700-47c0cb75-f4d8-422b-93f0-6ddeae4315ad.png" width="450">

We must correct some shrinkwrap, probably the root link and the other links directly constrained to it.

@fiorisi @traversaro @mfussi66  @salvi-mattia @Nicogene

**Comment by Mick3Lozzo** [comment]
> We must correct some shrinkwraps, probably the root link and the other links directly constrained to it.
> 
> @fiorisi @traversaro @mfussi66 @salvi-mattia @Nicogene

Done, both in Creo 7 and in Creo 9 shrink-wraps, we can generate e new URDF @Nicogene.

cc @fiorisi @traversaro @mfussi66 @salvi-mattia

**Comment by Mick3Lozzo** [comment]
Resolved, and as a bonus, I resolved some other inconsistencies I found on the shoulders.

<img src="https://user-images.githubusercontent.com/15085666/212023007-33d7faa6-90e4-49f9-a0de-641c67f905ce.png" width="450">

<img src="https://user-images.githubusercontent.com/15085666/212023116-3b29fd16-c61e-4739-b5d5-323f93d260ec.png" width="450">

<img src="https://user-images.githubusercontent.com/15085666/212023140-667fa0f1-244c-4ec6-bd45-5ce16760e90f.png" width="450">

We can re-generate the URDF again (until the next bug).

@fiorisi @traversaro @mfussi66 @salvi-mattia @Nicogene
